services:
  user-service:
    networks:
      - app_net
    build:
      context: ./User
      dockerfile: Dockerfile
    ports:
      - "5050:80"
      - "7150:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=userdb;Username=postgres;Password=postgres
    volumes:
      - ./data/keys:/keys
    env_file: User/.env
    depends_on:
      db:
        condition: service_healthy
      keycloak:
        condition: service_healthy

  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: userdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak-db:
    image: postgres:16
    networks:
      - app_net
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak && psql -U keycloak -d keycloak -c 'SELECT 1' -t -v ON_ERROR_STOP=1"]
      interval: 5s
      timeout: 5s
      retries: 10

  keycloak:
    networks:
      - app_net
    image: quay.io/keycloak/keycloak:24.0
    command: 
      - "start-dev"
      - "--import-realm"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 20s
      timeout: 10s
      retries: 5
    volumes:
      - ./keycloak-realm.json:/opt/keycloak/data/import/realm.json
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://keycloak-db:5432/keycloak?sslmode=disable&connectTimeout=5&socketTimeout=5"
      QUARKUS_DATASOURCE_JDBC_MIN_SIZE: "2"
      QUARKUS_DATASOURCE_JDBC_MAX_SIZE: "10"
      QUARKUS_DATASOURCE_USERNAME: keycloak
      QUARKUS_DATASOURCE_PASSWORD: password
      QUARKUS_DATASOURCE_DB_KIND: postgresql
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB_INITIALIZE: "true"
      KC_TRANSACTION_XA_ENABLED: "false"
      QUARKUS_DATASOURCE_JDBC_RECONNECT_INTERVAL: "2s"
      QUARKUS_DATASOURCE_JDBC_RECONNECT_ATTEMPTS: "10"
      QUARKUS_DATASOURCE_JDBC_VALIDATION_QUERY_SQL: "SELECT 1"
      QUARKUS_DATASOURCE_JDBC_VALIDATION_TIMEOUT: "5s"
      JAVA_OPTS: "-Dkc.db.tx.xa-enabled=false -Dkc.db.connections-initial-size=2 -Dkc.db.connections-min-size=2"
    ports:
      - "8080:8080"
    depends_on:
      keycloak-db:
        condition: service_healthy

volumes:
  postgres_data:
  keycloak_db_data:

networks:
  app_net:
    driver: bridge
